spring:
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Df#7*pX@5sW1zQr

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate.globally_quoted_identifiers: false

server:
  port: 8080