spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

info:
  application:
    name: ${spring.application.name}
    description: Challenge III - IURY DE MATTOS [DEV]

logging:
  file:
    name: ./logs/gateway.log

server:
  port: 8080